### ISSUE TITLE
Lable color not chnaging and lable getting diapiar on click on slider

### ISSUE THREAD

**Issue by Deepab23** [charlieroberts/interface.js#17]
Label color not changing and label getting disappear on click on slider

see here
http://garhwalonline.com/eval/ at the end love and fun label

**Comment by Deepab23** [comment]
Hi can any one reply

**Comment by charlieroberts** [comment]
Hello,

Please use the "label" property of the slider widget to define text to display in a slider or button. You can look at the examples on the homepage (http://www.charlie-roberts.com/interface/) to see this in action.

More generally, there's no way at the moment to place two widgets on top of each other and expect reliable behavior in Interface.js. - Charlie
